In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"C:\Users\priya\Downloads\Data Analytics Projects\Pharma_Marketing_Analytics\Data\data_drug_Raw_Data.csv")

In [4]:
df.head()

,Unnamed: 0,accID,accType,accSize,accTargets,district,month,sales,qty,strategy1,strategy2,strategy3,salesVisit1,salesVisit2,salesVisit3,salesVisit4,salesVisit5,compBrand
0,1,XYZ-987002,Pharmacy,700,25,3,2013-10-01,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
1,2,XYZ-987002,Pharmacy,700,25,3,2013-11-01,852365,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,75000.0,4
2,3,XYZ-987002,Pharmacy,700,25,3,2013-12-01,2557096,25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4
3,4,XYZ-987002,Pharmacy,700,25,3,2014-01-01,4261826,41,0.0,0.0,0.0,0.0,825000.0,300000.0,0.0,0.0,4
4,5,XYZ-987002,Pharmacy,700,25,3,2014-02-01,5966556,57,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4

In [5]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2976 entries, 0 to 2975
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   2976 non-null   int64
 1   accID        2976 non-null   object
 2   accType      2976 non-null   object
 3   accSize      2976 non-null   int64
 4   accTargets   2976 non-null   int64
 5   district     2976 non-null   int64
 6   month        2976 non-null   object
 7   sales        2976 non-null   int64
 8   qty          2976 non-null   int64
 9   strategy1    2976 non-null   float64
 10  strategy2    2976 non-null   float64
 11  strategy3    2976 non-null   float64
 12  salesVisit1  2976 non-null   float64
 13  salesVisit2  2976 non-null   float64
 14  salesVisit3  2976 non-null   float64
 15  salesVisit4  2976 non-null   float64
 16  salesVisit5  2976 non-null   float64
 17  compBrand    2976 non-null   int64
dtypes: float64(8), int64(7), object(3)
memory usage: 418.6+ KB

,Unnamed: 0,accSize,accTargets,district,sales,qty,strategy1,strategy2,strategy3,salesVisit1,salesVisit2,salesVisit3,salesVisit4,salesVisit5,compBrand
count,2976.000000,2976.000000,2976.000000,2976.0,2.976000e+03,2976.000000,2.976000e+03,2.976000e+03,2.976000e+03,2.976000e+03,2.976000e+03,2.976000e+03,2.976000e+03,2976.000000,2976.000000
mean,1488.500000,364.233871,15.016129,3.0,4.251100e+06,40.488239,3.332208e+04,1.593997e+05,6.924983e+03,3.054435e+04,4.705393e+05,4.342994e+05,1.645665e+04,3402.217742,4.166667
std,859.241526,417.462184,17.408423,0.0,7.564508e+06,72.137995,1.681500e+05,4.017645e+05,8.911939e+04,2.406703e+05,7.899979e+05,7.607787e+05,8.999703e+04,20711.524380,0.372741
min,1.000000,0.000000,1.000000,3.0,-5.540374e+06,-21.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,4.000000
25%,744.750000,60.000000,2.000000,3.0,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,4.000000
50%,1488.500000,240.000000,9.500000,3.0,8.523650e+05,8.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.500000e+05,7.500000e+04,0.000000e+00,0.000000,4.000000
75%,2232.250000,522.500000,20.250000,3.0,5.114191e+06,49.000000,0.000000e+00,1.894950e+04,0.000000e+00,0.000000e+00,6.000000e+05,6.000000e+05,0.000000e+00,0.000000,4.000000
max,2976.000000,2460.000000,102.000000,3.0,5.199428e+07,500.000000,2.662031e+06,3.161384e+06,2.236600e+06,6.750000e+06,7.125000e+06,6.075000e+06,1.125000e+06,375000.000000,5.000000

In [6]:
df.shape

(2976, 18)

In [23]:
df.columns

Index(['accid', 'acctype', 'accsize', 'acctargets', 'district', 'month',
       'sales', 'qty', 'strategy1', 'strategy2', 'strategy3', 'salesvisit1',
       'salesvisit2', 'salesvisit3', 'salesvisit4', 'salesvisit5',
       'compbrand'],
      dtype='object')

In [24]:
df.isnull().sum()

accid          0
acctype        0
accsize        0
acctargets     0
district       0
month          0
sales          0
qty            0
strategy1      0
strategy2      0
strategy3      0
salesvisit1    0
salesvisit2    0
salesvisit3    0
salesvisit4    0
salesvisit5    0
compbrand      0
dtype: int64

In [12]:
df.fillna(df.mean(numeric_only=True), inplace=True)

In [13]:
df.duplicated().sum()

0

In [15]:
df.drop_duplicates(inplace=True)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2964 entries, 0 to 2975
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   accid        2964 non-null   object
 1   acctype      2964 non-null   object
 2   accsize      2964 non-null   int64
 3   acctargets   2964 non-null   int64
 4   district     2964 non-null   int64
 5   month        2964 non-null   datetime64[ns]
 6   sales        2964 non-null   int64
 7   qty          2964 non-null   int64
 8   strategy1    2964 non-null   float64
 9   strategy2    2964 non-null   float64
 10  strategy3    2964 non-null   float64
 11  salesvisit1  2964 non-null   float64
 12  salesvisit2  2964 non-null   float64
 13  salesvisit3  2964 non-null   float64
 14  salesvisit4  2964 non-null   float64
 15  salesvisit5  2964 non-null   float64
 16  compbrand    2964 non-null   int64
dtypes: datetime64[ns](1), float64(8), int64(6), object(2)
memory usage: 416.8+ KB

In [17]:
df['month'] = pd.to_datetime(df['month'])

In [18]:
df.columns = df.columns.str.lower().str.strip()

In [26]:
df.describe()

,accsize,acctargets,district,sales,qty,strategy1,strategy2,strategy3,salesvisit1,salesvisit2,salesvisit3,salesvisit4,salesvisit5,compbrand
count,2964.000000,2964.000000,2964.0,2.964000e+03,2964.000000,2.964000e+03,2.964000e+03,2.964000e+03,2.964000e+03,2.964000e+03,2.964000e+03,2.964000e+03,2964.000000,2964.000000
mean,364.555331,15.030027,3.0,4.274839e+06,40.680499,3.340572e+04,1.600450e+05,6.953019e+03,3.059211e+04,4.711285e+05,4.343877e+05,1.637146e+04,3415.991903,4.166329
std,418.164203,17.436838,0.0,7.569924e+06,72.219148,1.684744e+05,4.024489e+05,8.929858e+04,2.411235e+05,7.912314e+05,7.618245e+05,8.992666e+04,20752.288294,0.372439
min,0.000000,1.000000,3.0,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,4.000000
25%,60.000000,2.000000,3.0,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,4.000000
50%,240.000000,9.500000,3.0,8.523650e+05,8.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.500000e+05,7.500000e+04,0.000000e+00,0.000000,4.000000
75%,530.000000,21.000000,3.0,5.114191e+06,49.000000,0.000000e+00,1.998200e+04,0.000000e+00,0.000000e+00,6.000000e+05,6.000000e+05,0.000000e+00,0.000000,4.000000
max,2460.000000,102.000000,3.0,5.199428e+07,500.000000,2.662031e+06,3.161384e+06,2.236600e+06,6.750000e+06,7.125000e+06,6.075000e+06,1.125000e+06,375000.000000,5.000000

In [21]:
df = df[df['sales'] >= 0]

In [22]:
df.drop(columns=['unnamed: 0'], inplace=True)

In [27]:
df.isnull().sum()
df.duplicated().sum()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2964 entries, 0 to 2975
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   accid        2964 non-null   object
 1   acctype      2964 non-null   object
 2   accsize      2964 non-null   int64
 3   acctargets   2964 non-null   int64
 4   district     2964 non-null   int64
 5   month        2964 non-null   datetime64[ns]
 6   sales        2964 non-null   int64
 7   qty          2964 non-null   int64
 8   strategy1    2964 non-null   float64
 9   strategy2    2964 non-null   float64
 10  strategy3    2964 non-null   float64
 11  salesvisit1  2964 non-null   float64
 12  salesvisit2  2964 non-null   float64
 13  salesvisit3  2964 non-null   float64
 14  salesvisit4  2964 non-null   float64
 15  salesvisit5  2964 non-null   float64
 16  compbrand    2964 non-null   int64
dtypes: datetime64[ns](1), float64(8), int64(6), object(2)
memory usage: 416.8+ KB

In [28]:
df = df[df['qty'] >= 0]

In [30]:
df.to_csv('../Data/cleaned_data.csv', index=False)